version: "3.1"

services:
  db:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: strapi
      POSTGRES_DB: article-blog
    ports:
      - 5432:5432
